name: Notify Slack
description: Notify Slack
inputs:
  slack_webhook_url:
    description: Slack webhook URL
    required: true
runs:
  using: composite
  steps:
    - uses: slackapi/slack-github-action@v1.23.0
      with:
        payload: |
          {
            "text": "Build result for ${{ github.repository }}",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "On *${{ github.event.repository.name }}* ran *${{ github.workflow }}* (${{ github.event.pull_request.title }}) for ${{ github.event.head_commit.author.name || github.actor }}: ${{ job.status }} [<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|result>]"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.slack_webhook_url }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
